const GET_REQUEST = "GET_REQUEST";
const GET_SUCCESS = "GET_SUCCESS";
const GET_FAIL = "GET_FAIL";
const USER_SIGNIN = "USER_SIGNIN";
const USER_SIGNOUT = "USER_SIGNOUT";
const PRODUCT_ADD = "PRODUCT_ADD";
const PRODUCT_REMOVE = "PRODUCT_REMOVE";
const SAVE_SHIPPING_ADDRESS = "SAVE_SHIPPING_ADDRESS"

export {
  GET_FAIL,
  GET_SUCCESS,
  GET_REQUEST,
  USER_SIGNIN,
  USER_SIGNOUT,
  PRODUCT_ADD,
  PRODUCT_REMOVE,
  SAVE_SHIPPING_ADDRESS
};
